name: CI/CD for MERN Stack

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "â˜ï¸ Checkout Repository"
        uses: actions/checkout@v2

      - name: "ğŸ”§ Setup Node.js"
        uses: actions/setup-node@v2.4.2
        with:
          node-version: 16

      - name: "ğŸ”§ Install npm@latest"
        run: npm i -g npm@latest

      - name: "ğŸ“¦ Install Dependencies"
        run: npm install

      - name: "ğŸ“Š Run Tests (if applicable)"
        run: npm test  # Adjust this command based on your testing setup

      - name: "ğŸ“¦ Build React App"
        run: npm run build

      - name: "ğŸš€ Deploy to Heroku (or your hosting platform)"
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Set this secret in your repository settings
          heroku_app_name: festiva-ucf  # Replace with your Heroku app name
          heroku_email: rjbarrioslll@gmail.com  # Replace with your Heroku account email
